// This slint file contains all the UI pages of the application.

import { Page, TemperatureBar, HumidityBar } from "widgets.slint";
import { HorizontalBox } from "std-widgets.slint";

export component TemperaturePage inherits Page {
    in property temperature-celsius <=> temperature-bar.value;
    in property humidity-percent <=> humidity-bar.value;

    HorizontalBox {
        temperature-bar := TemperatureBar {}
        humidity-bar := HumidityBar {}
    }
}
